# Generated by Django 4.2 on 2023-05-14 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Users",
            fields=[
                (
                    "id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="记录编号"
                    ),
                ),
                (
                    "userName",
                    models.CharField(
                        db_column="user_name", max_length=32, verbose_name="用户账号"
                    ),
                ),
                ("passWord", models.CharField(max_length=32, verbose_name="用户密码")),
            ],
            options={
                "db_table": "users",
            },
        ),
        migrations.CreateModel(
            name="Images",
            fields=[
                (
                    "id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="记录编号"
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="图片名称")),
                ("img", models.BinaryField(blank=True, null=True, verbose_name="图片数据")),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_column="user_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.users",
                    ),
                ),
            ],
            options={
                "db_table": "images",
            },
        ),
    ]
