# Generated by Django 4.2 on 2023-05-31 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="images",
            name="img",
            field=models.ImageField(
                blank=True, null=True, upload_to="", verbose_name="图片数据"
            ),
        ),
    ]
